# Tells GitHub Pages to build using the clean, responsive Cayman layout
theme: jekyll-theme-cayman
remote_theme: jekyll-theme-cayman

# The main name and subtitle displayed on search engine tabs
title: Device Driver Interview Prep Vault
description: Study notes dashboard for low-level development.
# Add this line so GitHub Pages processes your custom named file
#include: [Embedded-Blog.md,Embedded-BlogQList.md,Embedded-BlogQAns.md]

# Forces GitHub to read your style sheet without needing front-matter dashes
sass:
  style: :compressed
